name: github-actions
on:
  push:
    branches:
      - main
jobs:
    Build:
        runs-on: ubuntu-latest
        env:
            BUILD_IMAGE: bedasoftware/ucfwealth-frontend:latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install deps
              run: yarn
            - run: cp shared/src/config.cloud.ts shared/src/config.ts
            - run: yarn build:web
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
            - run: docker run --rm --privileged tonistiigi/binfmt --install all
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}
            - run: >-
                  docker buildx build --platform linux/arm64,linux/amd64
                  --push -t ${{ env.BUILD_IMAGE }} .
    Deploy:
      environment: Staging
      runs-on: ubuntu-latest
      needs: ["Build"]
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      steps:
        - run: python -m pip install --upgrade awscli
        - run: curl -LO "https://dl.k8s.io/release/v1.25.1/bin/linux/amd64/kubectl"
        - run: aws eks --region us-east-2 update-kubeconfig --name  hadleylaboratory
        - run: kubectl --namespace staging rollout restart deployment.apps/frontend
