name: github-actions
on: [push]
jobs:
    Build:
        runs-on: ubuntu-latest
        env:
            BUILD_IMAGE: bedasoftware/ucfwealth-frontend:latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install deps
              run: yarn
            - run: yarn build:web
            - run: cp shared/src/config.cloud.ts shared/src/config.ts
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
            - run: docker run --rm --privileged tonistiigi/binfmt --install all
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}
            - run: >-
                  docker buildx build --platform linux/arm64,linux/amd64
                  --push -t ${{ env.BUILD_IMAGE }} .
